/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        try (var scanner = new Scanner(System.in)) {
            var input = scanner.tokens().toString();
            System.out.println(expr(input));
        }
    };

    public static int expr(String input) {
        var parser = new Parser(input);
        ASTNode ast = parser.parse();
        return ast.evaluate();
    }
}